# Generated by Django 3.1.4 on 2021-01-26 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_userpostrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewers',
            field=models.ManyToManyField(related_name='post_viewers', through='blog.UserPostRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
