# Generated by Django 3.1.4 on 2021-01-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210126_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'meh'), (2, 'ok'), (3, 'fine'), (4, 'good'), (5, 'amazing')], null=True),
        ),
    ]
