# Generated by Django 3.1.4 on 2021-01-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210128_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_modify_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
