# Generated by Django 3.1.4 on 2021-04-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210408_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
