# Generated by Django 3.1.4 on 2021-03-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, null=None)),
                ('user_email', models.EmailField(db_index=True, max_length=100)),
            ],
        ),
    ]
