# Generated by Django 3.1.4 on 2021-03-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_email',
            new_name='email',
        ),
    ]
