# Generated by Django 3.1.4 on 2021-04-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0002_auto_20210331_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
